#!/usr/bin/env node
// Unified test runner. Replaces bin/run-*.sh + bin/test-all.sh.
//
// Usage: node scripts/test.mjs <suite> [options]
//   suite ∈ optimize | passing | warning | all
//
// Env / CLI options:
//   --limit=N            cap to N tests per suite
//   --pattern=<substr>   only test names containing <substr>
//   --semantic           normalise $N placeholders before diffing
//   --verbose            show per-test detail
//
// What each suite does mirrors purescript/tests/TestCompiler.hs:
//   optimize: compile -> our codegen -> diff bytes against .out.js
//   passing : compile -> our codegen replaces Main -> node -> expect "Done"
//   warning : compile -> our codegen -> node --check (parse only)

import { spawn, spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, rmSync, cpSync, copyFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT = dirname(__dirname);
const TESTS_DIR = join(PROJECT, 'tests/upstream');
const PRELUDE_POOL = join(PROJECT, 'prelude-pool/.spago/p');
const PURSJS_MAIN = join(PROJECT, 'output/PursJS.Main/index.js');
const KNOWN_FAILURES_FILE = join(PROJECT, 'tests/known-failures.json');

// Tests we know fail at the current pin. The runner subtracts these
// from each suite's failure count before deciding whether to exit
// non-zero, so CI doesn't go red on documented-known issues. Any
// unexpected failure still trips CI.
const knownFailures = existsSync(KNOWN_FAILURES_FILE)
  ? JSON.parse(readFileSync(KNOWN_FAILURES_FILE, 'utf8'))
  : {};

// fails entries look like "Name:diff" or "Name:codegen-timeout" — match
// by the leading test name only.
function partitionFails(suiteName, fails) {
  const allowed = knownFailures[suiteName] || {};
  const expected = [], unexpected = [];
  for (const f of fails) {
    const testName = f.split(':')[0];
    (testName in allowed ? expected : unexpected).push(f);
  }
  return { expected, unexpected };
}

// ── arg parsing ────────────────────────────────────────────────────────
const args = process.argv.slice(2);
const suite = args[0];
const opts = Object.fromEntries(args.slice(1)
  .filter(a => a.startsWith('--'))
  .map(a => {
    const [k, v = '1'] = a.replace(/^--/, '').split('=');
    return [k, v];
  }));
const limit = parseInt(opts.limit || '0', 10);
const pattern = opts.pattern || '';
const semantic = opts.semantic === '1';
const verbose = opts.verbose === '1';

if (!['optimize', 'passing', 'warning', 'all'].includes(suite)) {
  console.error('Usage: node scripts/test.mjs <optimize|passing|warning|all> [options]');
  process.exit(2);
}

// ── prelude source pool (one-time discovery) ───────────────────────────
function collectPreludeSources() {
  if (!existsSync(PRELUDE_POOL)) {
    console.error(`Prelude pool not found at ${PRELUDE_POOL}.`);
    console.error('Run: cd prelude-pool && spago build');
    process.exit(1);
  }
  const sources = [];
  function walk(dir) {
    for (const entry of readdirSync(dir)) {
      const p = join(dir, entry);
      const st = statSync(p);
      if (st.isDirectory()) walk(p);
      else if (p.endsWith('.purs')) sources.push(p);
    }
  }
  walk(PRELUDE_POOL);
  return sources;
}

// ── helpers ────────────────────────────────────────────────────────────
function stripPursPrefix(s) {
  return s.split('\n')
    .filter(l => !l.startsWith('// Generated by') && !l.startsWith('//# sourceMappingURL='))
    .join('\n');
}

// Renumber $N + $tco_doneN placeholders to 0..M in order of first appearance.
function normalizeFreshNames(s) {
  const map = new Map();
  let counter = 0;
  return s.replace(/\$\d+|\$tco_done\d+/g, (m) => {
    if (!map.has(m)) {
      const prefix = m.startsWith('$tco_done') ? '$tco_done' : '$';
      map.set(m, prefix + (counter++));
    }
    return map.get(m);
  });
}

// Synchronous child-process run with a timeout (kill -9 on expiry).
function runWithTimeout(cmd, argv, opts, timeoutMs) {
  // We use spawn so we can kill on timeout; collect stdout/stderr.
  return new Promise((resolve) => {
    const child = spawn(cmd, argv, opts);
    let stdout = '', stderr = '';
    child.stdout?.on('data', d => stdout += d.toString());
    child.stderr?.on('data', d => stderr += d.toString());
    let timedOut = false;
    const t = setTimeout(() => {
      timedOut = true;
      child.kill('SIGKILL');
    }, timeoutMs);
    child.on('close', (code) => {
      clearTimeout(t);
      resolve({ code, stdout, stderr, timedOut });
    });
    child.on('error', (err) => {
      clearTimeout(t);
      resolve({ code: -1, stdout, stderr: stderr + err.message, timedOut });
    });
  });
}

// Invoke `purs compile` for one test file + companions, using the shared
// pre-compiled prelude output in --output.
async function pursCompile(outputDir, mainPurs, companions, preludeSources, opts = {}) {
  const allArgs = ['compile', '--codegen', 'js,corefn', '-o', outputDir, mainPurs, ...companions, ...preludeSources];
  const res = await runWithTimeout('purs', allArgs, { stdio: ['ignore', 'pipe', 'pipe'] }, opts.timeoutMs ?? 120000);
  return res;
}

// Invoke our codegen via node on the given corefn.json. Optional flags
// (e.g. --with-comments).
async function runOurCodegen(corefnPath, extraFlags = []) {
  const script = `
import { main } from '${PURSJS_MAIN}';
process.argv = [process.argv[0], 'main', '${corefnPath}'${extraFlags.map(f => `, '${f}'`).join('')}];
main();
`;
  const res = await runWithTimeout('node', ['--input-type=module', '-e', script], { stdio: ['ignore', 'pipe', 'pipe'] }, 60000);
  return res;
}

// Pre-compile the prelude once and reuse via hardlink-copy per test.
function preCompilePrelude(preludeSources) {
  const sharedOut = mkdtempSync(join(tmpdir(), 'pursjs-shared-'));
  console.log('Pre-compiling prelude pool...');
  const r = spawnSync('purs', ['compile', '--codegen', 'js,corefn', '-o', sharedOut, ...preludeSources], { stdio: 'pipe' });
  if (r.status !== 0) {
    console.error('Pre-compile failed:');
    console.error(r.stderr?.toString().split('\n').slice(-15).join('\n'));
    process.exit(1);
  }
  return sharedOut;
}

function makeWorkdir(prefix, sharedOut) {
  const wd = mkdtempSync(join(tmpdir(), prefix));
  // Hardlink-copy the shared prelude output. cp -al on macOS preserves links.
  spawnSync('cp', ['-al', sharedOut, join(wd, 'output')]);
  return wd;
}

function discoverTests(category) {
  const dir = join(TESTS_DIR, category);
  if (!existsSync(dir)) {
    console.error(`tests/upstream/${category} not found. Run: npm run sync-tests`);
    process.exit(1);
  }
  return readdirSync(dir)
    .filter(f => f.endsWith('.purs'))
    .map(f => f.slice(0, -5))
    .filter(name => !pattern || name.includes(pattern))
    .sort();
}

// ── optimize suite ────────────────────────────────────────────────────
async function runOptimize(preludeSources, sharedOut) {
  const tests = discoverTests('optimize');
  const subset = limit ? tests.slice(0, limit) : tests;
  let pass = 0, fail = 0, errored = 0;
  const fails = [];
  for (const name of subset) {
    const pursPath = join(TESTS_DIR, 'optimize', name + '.purs');
    const expectedPath = join(TESTS_DIR, 'optimize', name + '.out.js');
    if (!existsSync(expectedPath)) continue;
    const wd = makeWorkdir('pursjs-opt-', sharedOut);
    const testPurs = join(wd, name + '.purs');
    copyFileSync(pursPath, testPurs);
    const foreignSrc = join(TESTS_DIR, 'optimize', name + '.js');
    if (existsSync(foreignSrc)) copyFileSync(foreignSrc, join(wd, name + '.js'));

    const cr = await pursCompile(join(wd, 'output'), testPurs, [], preludeSources);
    if (cr.code !== 0) {
      errored++; fails.push(`${name}:purs-compile`); rmSync(wd, { recursive: true, force: true }); continue;
    }
    const corefn = join(wd, 'output/Main/corefn.json');
    if (!existsSync(corefn)) {
      errored++; fails.push(`${name}:no-corefn`); rmSync(wd, { recursive: true, force: true }); continue;
    }
    const oursRes = await runOurCodegen(corefn, ['--with-comments']);
    rmSync(wd, { recursive: true, force: true });
    if (oursRes.code !== 0) {
      errored++; fails.push(`${name}:codegen` + (oursRes.timedOut ? '-timeout' : ''));
      continue;
    }
    let oursStripped = stripPursPrefix(oursRes.stdout);
    let refStripped = stripPursPrefix(readFileSync(expectedPath, 'utf8'));
    if (semantic) { oursStripped = normalizeFreshNames(oursStripped); refStripped = normalizeFreshNames(refStripped); }
    if (oursStripped === refStripped) {
      pass++; if (verbose) console.log(`OK   ${name}`);
    } else {
      fail++; console.log(`DIFF ${name}`); fails.push(`${name}:diff`);
    }
  }
  console.log(`\nOptimize: ${pass} pass, ${fail} differ, ${errored} errored`);
  return { pass, fail, errored, fails };
}

// ── passing suite ─────────────────────────────────────────────────────
async function runPassing(preludeSources, sharedOut) {
  const tests = discoverTests('passing');
  const subset = limit ? tests.slice(0, limit) : tests;
  let pass = 0, noDone = 0, codegenFail = 0, runtimeFail = 0, pursFail = 0;
  const fails = [];

  for (const name of subset) {
    const pursPath = join(TESTS_DIR, 'passing', name + '.purs');
    const companionDir = join(TESTS_DIR, 'passing', name);
    const companions = existsSync(companionDir)
      ? readdirSync(companionDir, { recursive: true })
          .filter(f => f.toString().endsWith('.purs'))
          .map(f => join(companionDir, f.toString()))
      : [];

    const wd = makeWorkdir('pursjs-pass-', sharedOut);
    const cr = await pursCompile(join(wd, 'output'), pursPath, companions, preludeSources);
    if (cr.code !== 0) {
      pursFail++; fails.push(`${name}:purs-compile`); rmSync(wd, { recursive: true, force: true }); continue;
    }
    const corefn = join(wd, 'output/Main/corefn.json');
    if (!existsSync(corefn)) {
      pursFail++; fails.push(`${name}:no-corefn`); rmSync(wd, { recursive: true, force: true }); continue;
    }

    const oursRes = await runOurCodegen(corefn);
    if (oursRes.code !== 0) {
      codegenFail++;
      fails.push(`${name}:codegen` + (oursRes.timedOut ? '-timeout' : ''));
      if (verbose) console.log(`CODEGEN ${name} (${oursRes.timedOut ? 'timeout' : oursRes.code})`);
      rmSync(wd, { recursive: true, force: true });
      continue;
    }
    writeFileSync(join(wd, 'output/Main/index.js'), oursRes.stdout);
    writeFileSync(join(wd, 'output/package.json'), '{"type":"module"}');
    writeFileSync(join(wd, 'output/index.js'),
      `import('./Main/index.js').then(({ main }) => main());`);

    const nodeRes = await runWithTimeout('node', [join(wd, 'output/index.js')], { stdio: ['ignore', 'pipe', 'pipe'] }, 60000);
    rmSync(wd, { recursive: true, force: true });
    if (nodeRes.code !== 0) {
      runtimeFail++; fails.push(`${name}:runtime`); continue;
    }
    const lastLine = nodeRes.stdout.trim().split('\n').pop();
    if (lastLine === 'Done') {
      pass++; if (verbose) console.log(`OK   ${name}`);
    } else {
      noDone++; fails.push(`${name}:no-done(${lastLine})`);
    }
  }

  console.log(`\nPassing: ${pass} pass, ${noDone + codegenFail + runtimeFail} fail (no-done=${noDone}, codegen=${codegenFail}, runtime=${runtimeFail}), ${pursFail} purs-err`);
  return { pass, fail: noDone + codegenFail + runtimeFail, errored: pursFail, fails };
}

// ── warning suite ─────────────────────────────────────────────────────
async function runWarning(preludeSources, sharedOut) {
  const tests = discoverTests('warning');
  const subset = limit ? tests.slice(0, limit) : tests;
  let pass = 0, codegenFail = 0, parseFail = 0, pursFail = 0;
  const fails = [];

  for (const name of subset) {
    const pursPath = join(TESTS_DIR, 'warning', name + '.purs');
    const wd = makeWorkdir('pursjs-warn-', sharedOut);
    const cr = await pursCompile(join(wd, 'output'), pursPath, [], preludeSources);
    if (cr.code !== 0) {
      pursFail++; fails.push(`${name}:purs-compile`); rmSync(wd, { recursive: true, force: true }); continue;
    }
    // Find the Main corefn (warning tests usually have Main, but not always).
    const mainCorefn = join(wd, 'output/Main/corefn.json');
    const corefn = existsSync(mainCorefn) ? mainCorefn : findFirstCorefn(join(wd, 'output'));
    if (!corefn) {
      pursFail++; fails.push(`${name}:no-corefn`); rmSync(wd, { recursive: true, force: true }); continue;
    }

    const oursRes = await runOurCodegen(corefn);
    if (oursRes.code !== 0) {
      codegenFail++; fails.push(`${name}:codegen` + (oursRes.timedOut ? '-timeout' : ''));
      rmSync(wd, { recursive: true, force: true }); continue;
    }
    const checkPath = join(wd, 'check.mjs');
    writeFileSync(checkPath, oursRes.stdout);
    const parseRes = spawnSync('node', ['--check', checkPath], { stdio: 'pipe' });
    rmSync(wd, { recursive: true, force: true });
    if (parseRes.status !== 0) { parseFail++; fails.push(`${name}:parse`); continue; }
    pass++; if (verbose) console.log(`OK   ${name}`);
  }

  console.log(`\nWarning: ${pass} pass, ${codegenFail + parseFail} fail (codegen=${codegenFail}, parse=${parseFail}), ${pursFail} purs-err`);
  return { pass, fail: codegenFail + parseFail, errored: pursFail, fails };
}

function findFirstCorefn(outputDir) {
  for (const e of readdirSync(outputDir)) {
    if (e === 'Prim' || e.startsWith('Prim.')) continue;
    const cf = join(outputDir, e, 'corefn.json');
    if (existsSync(cf)) return cf;
  }
  return null;
}

// ── main ──────────────────────────────────────────────────────────────
(async () => {
  console.log('Building codegen...');
  const buildRes = spawnSync('spago', ['build'], { stdio: 'pipe' });
  if (buildRes.status !== 0) {
    console.error('spago build failed:');
    console.error(buildRes.stderr?.toString());
    process.exit(1);
  }

  const preludeSources = collectPreludeSources();
  const sharedOut = preCompilePrelude(preludeSources);

  // Pre-warm node ESM cache
  await runWithTimeout('node', ['--input-type=module', '-e', `import('${PURSJS_MAIN}')`], { stdio: 'ignore' }, 30000);

  const results = {};
  if (suite === 'all' || suite === 'optimize') results.optimize = await runOptimize(preludeSources, sharedOut);
  if (suite === 'all' || suite === 'passing') results.passing = await runPassing(preludeSources, sharedOut);
  if (suite === 'all' || suite === 'warning') results.warning = await runWarning(preludeSources, sharedOut);

  rmSync(sharedOut, { recursive: true, force: true });

  // Classify each suite's failures into expected (known) vs unexpected
  // (regressions). CI green-lights iff there are no unexpected fails.
  const verdicts = {};
  for (const [k, r] of Object.entries(results)) {
    const fails = r.fails || [];
    const { expected, unexpected } = partitionFails(k, fails);
    verdicts[k] = { ...r, expected, unexpected };
  }

  if (suite === 'all') {
    console.log('\n═════════════════════════════════════════════════════════════');
    console.log('ROLL-UP');
    console.log('═════════════════════════════════════════════════════════════');
    for (const [k, v] of Object.entries(verdicts)) {
      const known = v.expected.length ? `  (known=${v.expected.length})` : '';
      const unexp = v.unexpected.length ? `  UNEXPECTED=${v.unexpected.length}` : '';
      console.log(`  ${k.padEnd(10)}  pass=${v.pass}  fail=${v.fail}  errored=${v.errored}${known}${unexp}`);
    }
  }

  // Report any unexpected fails so CI logs explain the red.
  const allUnexpected = Object.entries(verdicts).flatMap(
    ([k, v]) => v.unexpected.map(f => `${k}/${f}`)
  );
  if (allUnexpected.length > 0) {
    console.log('\nUnexpected failures (not in tests/known-failures.json):');
    for (const f of allUnexpected) console.log(`  ${f}`);
    console.log('\nIf this is a real regression, fix it. If the failure is expected for a new');
    console.log('reason, add an entry to tests/known-failures.json explaining why.');
  }

  process.exit(allUnexpected.length > 0 ? 1 : 0);
})();
